package javaCore.ZZGconcorrencia.test;

import javaCore.ZZGconcorrencia.dominio.Quote;
import javaCore.ZZGconcorrencia.service.StoreServiceWithDiscount;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

public class CompletabletableFutureTest05 {
    public static void main(String[] args) {
        StoreServiceWithDiscount service = new StoreServiceWithDiscount();
        seachPricesWithDiscountAsync(service);
    }


    private static void seachPricesWithDiscountAsync(StoreServiceWithDiscount service) {
        long start = System.currentTimeMillis();

        List<String> stores = List.of("Store 1", "Store 2", "Store 3", "Store 4");

        List<CompletableFuture<String>> completableFutures = stores.stream()
                //Getting the price async storeName : price: discountCode
                .map(s -> CompletableFuture.supplyAsync(() -> service.getPriceSync(s)))
                //Instatiating a new QUote from the string generated by getPriceSync
                .map(cf -> cf.thenApply(Quote::newQuote))
                .map(cf -> cf.thenCompose(quote -> CompletableFuture.supplyAsync(() -> service.applyDiscount(quote))))
                .collect(Collectors.toList());

CompletableFuture

        long end = System.currentTimeMillis();
        System.out.printf("Tempo para pesquisar preços assincronamente: %dms%n", (end - start));
    }

}
